apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend-deploy
    app: capitec-microservice-application
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: backend-pod
      app: capitec-microservice-application
  template:
    metadata:
      name: backend-pod
      labels:
        name: backend-pod
        provider: spring-boot
        app: capitec-microservice-application
    spec:
      containers:
      - name: backend-pod
        image: thapeloseema/capitec-user-service:backend-amd64
        ports: 
          - containerPort: 8080