apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: capitec-microservice-application
spec:
  containers:
  - name: postgres
    image: postgres
    ports: 
      - containerPort: 5432
    env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"