apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    provider: postgres
    app: capitec-microservice-application
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: db-pod
    app: capitec-microservice-application