apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    provider: angular
    app: capitec-microservice-application
spec:
  containers:
  - name: frontend-pod
    image: thapeloseema/capitec-user-service:frontend-amd64
    ports: 
      - containerPort: 4200
